### ISSUE TITLE
Extensibility of HackerRank Advanced SQL Problem #2 Solution

### ISSUE THREAD

**Issue by dabricksta** [CuriosityLeonardo/HackerrankCertifications#2]
Hi Leonard, I appreciate your SQL tutorials on YT. Regarding the solution for the "SQL ADVANCED Certification Part 2 on Hackerrank | Crypto Market Transactions Monitoring" (https://www.youtube.com/watch?v=-lGJvfuqAHY), I am little confused on the third CTE with the sequences subquery (reproduced below).

```
... ,sequences as ( 
SELECT 
		*
FROM    difference
WHERE rownumber IN(
SELECT 
		rownumber 
FROM    rn
UNION
SELECT rownumber - 1 as rownumber
FROM   rn
 )
--order by sender,dt
) ...
```

Is this solution extensible to a similar data set with arbitrary numbers of suspicious transactions per group? Eg. 10 suspicious transactions that match the criteria defined in the problem. If so, how? From watching the YT tutorial it seems like the logic only extends to suspicious transactions of 3 per group (same sender, time limit, volume of $, etc). 

Of course this works for the particular data set in the problem, however I would be curious on how to create a scalable solution in pure SQL.

Thanks Leonard! Appreciate you and your excellent work.

PS: The links in the YT video for the code and database on GH both point to the database

**Comment by CuriosityLeonardo** [comment]
Hi dabricksta

Thanks for this very intelligently formulated question. Its always great to get input from smart people like you :)
You are absolutely right, as of right now, it cannot detect an arbitrary number of suspicious transactions per group.
How I would extent it is like this:
I would create another CTE after the sequences CTE. Something like that 

`
SELECT
            ROW_NUMBER() OVER(PARTITION BY sender ORDER BY rownumber) as susp_transaction_number,  
            *  
FROM sequences
`

Then in the final output, I would group the results by sender (as it already is) and by susp_transaction_number (from the new CTE).

This way we can catch multiple suspicious transactions from the same sender

Have a good one and thanks again for your question!

P.S.: I corrected the links in the description, thanks!

**Comment by dabricksta** [comment]
Okay, interesting, so would that catch an arbitrary number of transactions per set (eg. 10 or 100 transactions in the time and dollar amount constraints)? Or would that be arbitrary _sets of suspicious transactions_ per sender, but still limited to up to 3 transactions per set? Just to be clear, I was asking about the former.

Thanks!

**Comment by CuriosityLeonardo** [comment]
Ah okay, I misunderstood you. It is both working now. 
It was extending to more than 3 per group already before. Now it is also working with arbitrary _sets of suspicious transactions_.

The 3 per group was just the maximum per Group due to the dataset. If I would have 100 per group in the dataset, it would also catch that. We didnt need to make any alterations for that.
Why were you thinking it would be limited to 3 per Group?
You can also change the dataset and include more than 3 per Group and try it out.

**Comment by dabricksta** [comment]
Oh very cool! My confusion is about how the logic for selecting all sus. transactions in a set, which I believe is below:
```
...
,sequences as ( 
SELECT 
		*
FROM    difference
WHERE rownumber IN(
SELECT 
		rownumber 
FROM    rn
UNION
SELECT rownumber - 1 as rownumber
FROM   rn
 ...
```

How does that select more than just two transactions (rownumber's transaction and rownumber-1's transaction?)

BTW I appreciate your time invested in these responses, so if I can't understand it eventually I will do as you suggest and reproduce the dataset in sqlite.com to play around with the code.

**Comment by CuriosityLeonardo** [comment]
I sse where your confusion is now. In order to understand it, you also have to consider the two CTEs before. In the rn CTE, whenever a transaction is < 60 minutes to the transaction before, Im getting the rownumber of that transaction. But due to how the lag() function is working from the first CTE, Im not catching the first transaction of the suspicious sequence in the rn CTE. Thats why I catch that with the difference CTE.
To get a better understanding for it easily, I can also recommend to you to run the CTEs incrementally. First you just run the first CTE, understand what the result is doing. Then the first + second CTE and so on.
Hope that helps :)
